### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [dwi336/Eleven#10]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by dwi336** [comment]
Thank you for the idea and your offer, but I think that here is not the right place for FAQ: I just forked from and provide a build of

https://github.com/LineageOS/android_packages_apps_Eleven

There is lack of documentation about LineageOS and it's apps. I suggest that you ask unter

https://www.reddit.com/r/LineageOS/

where there is the best place to provide help to users.

Thank you,

dwi336
