### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by bene64** [dwi336/Eleven#19]
Hi @dwi336,

do you have any plans to maintain this fork of Eleven? 

I ask, because in https://gitlab.com/fdroid/fdroiddata/-/issues/1776 there are considerations wether to re-include this app or not.

**Comment by dwi336** [comment]
Hi bene64,
in general I continue building the app, if there where (greater) changes in the mainline. A distribution via f-droid is not intended.

**Comment by bene64** [comment]
Ok, thanks for your answer. 
I'll add a clarification at https://gitlab.com/fdroid/fdroiddata/-/issues/1776 and close this issue here.
