### ISSUE TITLE
Icon / Logo design proposal

### ISSUE THREAD

**Issue by s-yous** [dwi336/Eleven#7]
Hello @dwi336  , 
I'm a graphic designer and i'm willing to design an icon and a logo for your application and i'm asking for your permission to do that and for your imagination about it , or should i design it as i like .

**Comment by dwi336** [comment]
Thank you for your request, but I just forked and provide a build from

https://github.com/LineageOS/android_packages_apps_Eleven

I do not want to change the design.

dwi336

**Comment by BAProductions** [comment]
> Hello @dwi336 ,
> I'm a graphic designer and i'm willing to design an icon and a logo for your application and i'm asking for your permission to do that and for your imagination about it , or should i design it as i like .

I take you up on the offer
